services:
  postgres:
    image: postgres:15
    container_name: postgres_chronicapp
    environment:
      POSTGRES_USER: chronicapp
      POSTGRES_PASSWORD: youtube2025
      POSTGRES_DB: chronic_pain_db
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    restart: always

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin_cjronicapp
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - postgres

volumes:
  db_data: